### ISSUE TITLE
Feature to allow set new context for retry

### ISSUE THREAD

**Issue by abhijitsinha1980** [hashicorp/go-retryablehttp#61] opened 2019-07-02 10:00 UTC
[entry.go.txt](https://github.com/hashicorp/go-retryablehttp/files/3349464/entry.go.txt)
Purpose is to set new context in request or pass context to be considered by retryableHttp library for next usage. We are setting timeout set on context and would like to retry with new context, as once timeout happens, in below code snippet req.context().Done() completes and library does not retry.

select {
		case <-req.Context().Done():
			return nil, req.Context().Err()
		case <-time.After(wait):
		}

Sample code attached (please rename by removing ".txt" from end.

**Comment by abhijitsinha1980** [comment] 2019-07-09 13:41
The issue can be resolved if in one of the callback - there can be a way to add a new context that can be checked against. Do you think this can be a possible and acceptable solution for this library ?

**Comment by ryanuber** [comment] 2019-09-20 18:57
Hi there! I'm not sure this totally makes sense. The lifecycle of a `*Request` in this library is the full process, from invocation to either a successful reply or some error. This spans multiple requests in failure cases. Allowing new contexts to be generated would break the semantics of `(*Request).WithContext()` in that cancelation of the context provided would not necessarily cancel the request as intended.

Is your intent to simply limit the time of individual HTTP requests? I believe you can actually configure that in the standard HTTP client. Would that satisfy your use case?

**Comment by ryanuber** [comment] 2019-12-06 00:48
Closing for now. Feel free to re-open if you have further questions!

**Closed by ryanuber** 2019-12-06 00:48 UTC
